pipeline {
    agent any
    environment {
        bbranch ="${Branch}".replace('origin/', '');
    }
    stages {
        stage('config'){
            steps {
                echo "${bbranch}";
                sh "curl -H 'Authorization: token ${githubToken}' -H 'Accept: application/vnd.github.v3.raw' -kLJ -o .env 'https://raw.githubusercontent.com/other-project2/zi-api/main/.env'";
                sh 'ls -al';
                echo Branch;
                echo 'git clone';
            }
        }
        stage('build') {
            // agent {
            //     docker { image 'node:16.19.0' }
            // }
            steps {
                sh 'echo 1'
                sh 'sh ./deployments/build.sh'
                echo 'build';
                sh 'sh ./deployments/docker.sh'
                echo 'docker';
            }
        }
        stage('finished') {
            steps {
                sh 'sh ./deployments/finished.sh'
                echo 'docker';
            }
        }
    }
}